'use strict';

export var
SET_VIEW = 'SET_VIEW',
FETCH_FEED_REQ = 'FETCH_FEED_REQ',
FETCH_FEED_RES = 'FETCH_FEED_RES',
FETCH_FEED_ERR = 'FETCH_FEED_ERR',
SCROLL_FEED_START = 'SCROLL_FEED_START',
SCROLL_FEED_STOP = 'SCROLL_FEED_STOP',
OPEN_FEED_ITEM_ACTIONS = 'OPEN_FEED_ITEM_ACTIONS',
CLOSE_FEED_ITEM_ACTIONS = 'CLOSE_FEED_ITEM_ACTIONS',
FETCH_ME_REQ = 'FETCH_ME_REQ',
FETCH_ME_RES = 'FETCH_ME_RES',
FETCH_ME_ERR = 'FETCH_ME_ERR',
PLAYER_START = 'PLAYER_START',
PLAYER_PAUSE = 'PLAYER_PAUSE',
PLAYER_SET_TRACK = 'PLAYER_SET_TRACK',
PLAYER_OPEN = 'PLAYER_OPEN',
PLAYER_CLOSE = 'PLAYER_CLOSE',
PLAYER_VISUALIZE = 'PLAYER_VISUALIZE';